### ISSUE TITLE
报文协议建议

### ISSUE THREAD

**Issue by Versocial** [evpeople/ChatRoom-Backend#1]
### 希望实现功能：
当服务器从用户0收到数据：
```
{
"to":{"用户1","用户2",...,"用户n"},
"dialog":"群聊id",
"type":"某类型"
"某类型":一个json结构
}
```
时，将
```
{
"from":"用户0",
"dialog":"群聊id",
"type":"某类型",
"某类型":一个json结构
}
```
发送给用户1到用户n.

### 例如：
服务器从username收到
```
{
"to":{"evpeople","verso"},
"dialog":"聊天大厅"
"type":"text",
"text":"xxxxxxxxxxxxx"
}
```
时，将
```
{
"from":"username",
"dialog":"聊天大厅",
"type":"text",
"text":"xxxxxxxxxxxxx"
}
```
发送到evpeople和verso（若不在线的则不发）

### 补充

报文为json结构，对于报文部分，实际上后端只需要更换头部中的to为from即可。
如果比较闲，可以给报文增加一个```"timeStamp":时间戳```的项。

另规定：当头部中"to":{}时发送到所有连接到服务器的用户。

若另有想法可以更改格式并跟前端说明。

**Comment by Versocial** [comment]
另外，希望将```User xxx coming``` 改成```{"from":"xxx","type":"coming"}```或类似合理方案。

**Comment by Versocial** [comment]
另外建议在user下线时也广播```{"from":"xxx","type":"leaving"}```,
然后user上线时向他发送所有在线的用户名```{"from":"@backend","type":"online","users":{"verso","evpeople"}}```
这样客户端可以判断用户是否在线。

**Comment by evpeople** [comment]
> 另外建议在user下线时也广播`{"from":"xxx","type":"coming"}`, 然后user上线时向他发送所有在线的用户名`{"from":"@backend","type":"online","users":{"verso","evpeople"}}` 这样客户端可以判断用户是否在线。

是否采用客户端向后端询问当前在线人数更合理，我将开发一个询问当前在线人数的API

**Comment by Versocial** [comment]
> > 另外建议在user下线时也广播`{"from":"xxx","type":"coming"}`, 然后user上线时向他发送所有在线的用户名`{"from":"@backend","type":"online","users":{"verso","evpeople"}}` 这样客户端可以判断用户是否在线。
> 
> 是否采用客户端向后端询问当前在线人数更合理，我将开发一个询问当前在线人数的API

可以，询问在线人数时也请提供给出在线名单

**Comment by evpeople** [comment]
目前的JSON格式是

```json
{
"to":["evpeople","verso"],
"dialog":"聊天大厅"
"type":"text",
"detail":"string"
}
```

主要修改是 to 的值更改为了数组
detail 目前只能是string，至少转发的时候转发的是  string 的内容，不过Golang string底层也是 []byte 所以可能问题不大。

这个键的名字 也确定为 detail ，根据Type 的值修改 键名可能需要引入第三方库，感觉收益不大，可以先测试一下图片发送再做，
并且图片发送还没有考虑加密的问题
