### ISSUE TITLE
提供用户查询当前在线人数/名单api

### ISSUE THREAD

**Issue by Versocial** [evpeople/ChatRoom-Backend#5]

**Comment by evpeople** [comment]
type 为“users"的信息，将在返回的信息中的Detail中返回所有的User，但是返回的User不一定真的还在线，因为用户离开后，需要服务端先给客户端发送一条信息，才能知道websocket断开了

**Comment by evpeople** [comment]
Detail返回的User 以 \n 作为分隔符
